
nats-url: "nats://localhost:4222"
database-url: "postgresql://root@localhost:26257/defaultdb?sslmode=disable"
http-addr: ":8080"
bleve-index-path: "/home/evadmin/projects/TodoFlow/projection-worker/data/index.bleve"
log-level: "debug"
metrics-addr: ":9090"
